### Numpy
**Numpy** is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

In [1]:
import numpy as np

In [2]:
## Creating Arrays
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [3]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [4]:
array_1d.shape  # Output: (5,)

(5,)

In [5]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


In [6]:
array_2d = np.reshape(array_1d, (5, 1))

In [7]:
array_2d 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
print(array_2d.shape)  # Output: (5, 1)

(5, 1)


In [9]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)
print(array_2d.shape)  # Output: (2, 3)


2D Array:
[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
np.arange(0, 10, 2)  # Output: [0 2 4 6 8]

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0, 10, 2).reshape(1, -1)  # Output: [[0 2 4 6 8]]

array([[0, 2, 4, 6, 8]])

In [15]:
np.arange(0, 10).reshape(10, 1)  # Output: [[0] [1] [2] [3] [4] [5] [6] [7] [8] [9]]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [17]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)
print("Shape of the array:", array_2d.shape)  # Output: (2, 3)
print("Number of dimensions:", array_2d.ndim)  # Output: 2
print("Data type of elements:", array_2d.dtype)  # Output: int64
print("Size of the array:", array_2d.size)  # Output: 6
print("Item size in bytes:", array_2d.itemsize)  # Output: 8 (for int64)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape of the array: (2, 3)
Number of dimensions: 2
Data type of elements: int64
Size of the array: 6
Item size in bytes: 8


In [18]:
## Vectorized Operations
# Element-wise addition
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_c = array_a + array_b

print("Element-wise addition:", array_c)  # Output: [5 7 9]

Element-wise addition: [5 7 9]


In [19]:
# Element-wise multiplication
array_d = array_a * array_b
print("Element-wise multiplication:", array_d)  # Output: [ 4 10 18]

Element-wise multiplication: [ 4 10 18]


In [20]:
# Element-wise subtraction
array_e = array_a - array_b
print("Element-wise subtraction:", array_e)  # Output: [-3 -3 -3]

Element-wise subtraction: [-3 -3 -3]


In [21]:
# Element-wise division
array_f = array_a / array_b
print("Element-wise division:", array_f)  # Output: [0.25 0.4 0.5]

Element-wise division: [0.25 0.4  0.5 ]


In [22]:
## Universal Functions
# Square root of each element
array_sqrt = np.sqrt(array_a)
print("Square root of each element:", array_sqrt)  # Output: [1.         1.41421356 1.73205081]

Square root of each element: [1.         1.41421356 1.73205081]


In [23]:
# Exponential of each element
array_exp = np.exp(array_a)
print("Exponential of each element:", array_exp)  # Output: [ 2.71828183  7.3890561  20.08553692]

Exponential of each element: [ 2.71828183  7.3890561  20.08553692]


In [24]:
# Sine of each element
array_sin = np.sin(array_a)
print("Sine of each element:", array_sin)  # Output: [ 0.84147098  0.90929743  0.14112001]

Sine of each element: [0.84147098 0.90929743 0.14112001]


In [25]:
# Cosine of each element
array_cos = np.cos(array_a)
print("Cosine of each element:", array_cos)  # Output: [ 0.54030231 -0.41614684 -0.9899925 ]


Cosine of each element: [ 0.54030231 -0.41614684 -0.9899925 ]


In [26]:
# Array Slicing
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 2D Array:")
print(array_2d)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
# Slicing the first row
first_row = array_2d[0, :]
print("Sliced first row:", first_row)

# Slicing the first column
first_column = array_2d[:, 0]
print("Sliced first column:", first_column)

Sliced first row: [1 2 3]
Sliced first column: [1 4 7]


In [28]:
array_2d[0][0]

np.int64(1)

In [29]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array_2d[1:, 1:]  # Slicing from the second row and second column onwards

array([[5, 6],
       [8, 9]])

In [31]:
array_2d[0:2, 0:2]  # Slicing the first two rows and first two columns

array([[1, 2],
       [4, 5]])

In [32]:
array_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [33]:
print(array_2d.shape)  # Output: (3, 4)
print(array_2d.ndim)  # Output: 2
print(array_2d.dtype)  # Output: int64
print(array_2d.size)  # Output: 12
print(array_2d.itemsize)  # Output: 4 (for int32)


(3, 4)
2
int64
12
8


In [34]:
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
array_2d[0, 0] = 10

In [36]:
array_2d


array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
## statistical operations
# Mean of the array
array_1d = np.array([1, 2, 3, 4, 5])
mean = np.mean(array_1d)
print("Mean of the array:", mean)  # Output: 3.0
# Median of the array
median = np.median(array_1d)
print("Median of the array:", median)  # Output: 3.0
# Standard deviation of the array
std_dev = np.std(array_1d)
print("Standard deviation of the array:", std_dev)  # Output: 1.4142135623730951
# Variance of the array
variance = np.var(array_1d)
print("Variance of the array:", variance)  # Output: 2.0
# Minimum value in the array
min_value = np.min(array_1d)
print("Minimum value in the array:", min_value)  # Output: 1
# Maximum value in the array
max_value = np.max(array_1d)
print("Maximum value in the array:", max_value)  # Output: 5
# Sum of the array
sum_value = np.sum(array_1d)
print("Sum of the array:", sum_value)  # Output: 15 
# Cumulative sum of the array
cumulative_sum = np.cumsum(array_1d)
print("Cumulative sum of the array:", cumulative_sum)  # Output: [ 1  3  6 10 15]

Mean of the array: 3.0
Median of the array: 3.0
Standard deviation of the array: 1.4142135623730951
Variance of the array: 2.0
Minimum value in the array: 1
Maximum value in the array: 5
Sum of the array: 15
Cumulative sum of the array: [ 1  3  6 10 15]


In [38]:
## Logical Operations
# Logical AND operation
array_a = np.array([True, False, True])
array_b = np.array([True, True, False])
logical_and = np.logical_and(array_a, array_b)
print("Logical AND:", logical_and)  # Output: [ True False False]

Logical AND: [ True False False]


In [39]:
# Logical OR operation
logical_or = np.logical_or(array_a, array_b)
print("Logical OR:", logical_or)  # Output: [ True  True  True]
# Logical NOT operation
logical_not = np.logical_not(array_a)
print("Logical NOT:", logical_not)  # Output: [False  True False]

Logical OR: [ True  True  True]
Logical NOT: [False  True False]


In [40]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[data > 5]  # Output: [ 6  7  8  9 10]

array([ 6,  7,  8,  9, 10])

In [41]:
data[(data < 5) & (data > 2)]  # Output: [3 4]

array([3, 4])

In [42]:
data[(data < 5) | (data > 2)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# not logical operation on data
data[~(data < 5) & (data > 2)]  # Output: [ 5,  6,  7,  8,  9, 10]

array([ 5,  6,  7,  8,  9, 10])